repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: 1.8.5
  hooks:
    # Make sure poetry configuration does not get committed in a broken state
    - id: poetry-check
    # Make sure lock file is up-to-date when committing changes
    - id: poetry-lock

- repo: local
  hooks:
    # Make sure requirements.txt file (used for CI pipeline) is always equal with pyprocect.toml
    - id: poetry-export-requirements
      name: Export requirements.txt
      entry: bash -c "poetry export -f requirements.txt --without-hashes --with dev -o requirements.txt"
      language: system
      files: ^pyproject.toml$