CS_W = 'commandScriptWindows'
CS_L = 'commandScriptLinux'
ENABLE_CS_W = 'enableCommandScriptWindows'
ENABLE_CS_L = 'enableCommandScriptLinux'
SET_AS_WORKING_DIR = 'setToolDirAsWorkingDir'
LAUNCH_SETTINGS = 'launchSettings'
TOOL_DIR = 'toolDirectory'
PRE_S = 'preScript'
POST_S = 'postScript'
INPUTS = 'inputs'
OUTPUTS = 'outputs'

VALID_JSON_PATH = 'rest_rce/test/tools/root/configuration.json'
INVALID_JSON_PATH = 'rest_rce/test/tools/root/syntax_invalid_configuration.json'
INVALID_KEY_JSON_PATH = 'rest_rce/test/tools/root/invalid_key_configuration.json'
POLY_VAlID_JSON_PATH = 'rest_rce/test/tools/poly/configuration.json'
