name: Run Pytest

on:
  push:
    branches:
      - test_retry

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run shared tests
        run: |
          source $VENV 
          pytest rest_rce/test/shared/

      - name: Run Linux tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          source $VENV 
          pytest rest_rce/test/linux/

      - name: Run Windows tests
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          source $VENV 
          pytest rest_rce/test/windows/
